//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.27 at 01:00:53 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://iproduct.org/notes", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package course.java.jaxb.model;
